version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/environments"
    schedule:
      interval: "daily"
    labels:
    - "terraform ğŸ—"
    - "dependency ğŸšš"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "actions ğŸ¬"
      - "dependency ğŸšš"